version: '3.1'

services:
    php:
        image: maciejslawik/php-fpm-xdebug:7.3
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    redis:
        image: bitnami/redis:latest
        ports:
            - ${REDIS_PORT}:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - redis_data:/bitnami

volumes:
    redis_data:
